triggers:
- description: null
  envs: []
  last_enabled_at: 2024-06-06 17:07:54.030632+00:00
  name: retrain model hourly
  pipeline_uuid: automatic_retraining
  schedule_interval: '@hourly'
  schedule_type: time
  settings:
    allow_blocks_to_fail: true
    create_initial_pipeline_run: true
    skip_if_previous_running: true
  sla: null
  start_time: 2024-06-05 18:30:00+00:00
  status: inactive
  token: 705f96c55a444b9cb5b3947f7937d41a
  variables: {}
